project:
  type: website
  output-dir: ../docs/
  

website:
  title: "cciGraphs"
  navbar:
    left:
      - href: https://donghyunkm.github.io/
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


editor:
  render-on-save: true
